docs: create icons doc
natura-cosmeticos/natds-js pull request #1239
Opened 2020-12-04 10:46 UTC by lauralucca

DSY-1667

## Summary

### Proposed changes

This PR brings the following changes:

- Doc file about how to use icons

### Related issue

[DSY-1667 - Criar Documentacão sobre utilização Ícones no ZH](https://natura.atlassian.net/browse/DSY-1667)

### Dependencies added/removed (if applicable)

No dependencies were added or removed for this change.

---

### Testing

N/A

#### How to test

N/A

#### Test configuration

N/A

---

## Checklist

- [ ] I have added corresponding labels to this PR (like bug, enhancement...);
- [ ] My commits follow the [Conventional Commits 1.0 Guidelines](https://www.conventionalcommits.org/en/v1.0.0/);
- [ ] My code follows the style guidelines of this project;
- [ ] I have performed a self-review of my own code;
- [ ] I have mapped technical debts found on my changes;
- [ ] I have made corresponding changes to the documentation (if applicable);
- [ ] My changes generate no new warnings or errors;

2020-12-04 13:00 UTC, arielwb requested changes

2020-12-04 17:02 UTC, lauralucca commented on packages/web/docs/icons.md
> +    name="filled-default-mockup"
Escolhi o que achei mais fofo ☺️

2020-12-04 17:02 UTC, lauralucca commented on packages/web/docs/icons.md
> +> For component detailed API and usage examples, check out the [docs](https://natds-web.prd.naturacloud.com/) of the component you are using.
Feito!

2020-12-04 17:02 UTC, lauralucca commented on packages/web/docs/icons.md
> +You can also install icons separately. Please check `natds-icons` [docs](./packages/icons/README.md) for more info.
Nossa, super tinha pensado isso e esqueci! Valeusss!

2020-12-07 20:56 UTC, Design-System-Natura approved these changes
LGTM ⭐

2020-12-07 21:00 UTC, yasminnvaz approved these changes
LGTM ⭐

2020-12-07 21:08 UTC, merged