feature(Text Field): add new component [WIP]
natura-cosmeticos/natds-js pull request #1351
Opened 2021-04-27 15:25 UTC by yasminnvaz

# Description

Create new component

## Type of change

- [x] Feat: A new feature (non-breaking change which adds functionality)
- [ ] Refactor: A code change that neither fixes a bug nor adds a feature
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected
- [ ] Docs: Documentation only changes

# How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or errors;
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] My commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) Guidelines;

2021-05-12 17:11 UTC, lauralucca commented on packages/react/src/components/Input/Input.props.ts
> +export interface BaseProps {
Seria bom adicionar o `aria-labelledby` e o `aria-label` no input e na label. Inclusive reforçar a regra de usar um ou o outro é mais uma oportunidade de exercitar aquilo que aprendemos sobre TS

2021-05-12 19:31 UTC, lauralucca requested changes

2021-05-12 19:31 UTC, lauralucca commented on packages/react/src/components/Input/Input.tsx
> +              data-testid="ds-input"
Mesma coisa que disse sobre o `testid` padrão acima.

2021-05-12 19:31 UTC, lauralucca commented on packages/react/src/components/Input/InputLabel/InputLabel.styles.ts
> +    marginBottom: theme.spacing.micro
Pelo que vi na ui doc a Label devia usar a tipografia `subtitle2`

2021-05-12 19:31 UTC, lauralucca commented on packages/react/src/components/Input/InputHelperText/InputHelperText.styles.ts
> +    marginTop: theme.spacing.micro,
Pelo que vi na ui doc a HelerText devia usar a tipografia `caption`

2021-05-12 19:31 UTC, lauralucca commented on packages/react/src/components/TextField/TextField.stories.tsx
> +  src: 'https://cdn.jsdelivr.net/npm/@naturacosmeticos/natds-react@2.0.0-alpha.DSY-1963.53.0/dist/assets/mastercard@2x.png',
Aqui é bom trocar pela imagem padrão que o Lucas pediu quando foi feita a primeira revisão da doc.

2021-05-13 18:02 UTC, arielwb approved these changes

2021-05-13 18:02 UTC, arielwb commented on packages/react/src/components/TextField/TextField.test.tsx
> +  it('should render correctly have a label', () => {
should render correctly when have a label

2021-05-13 18:02 UTC, arielwb commented on packages/react/src/components/TextField/TextField.test.tsx
> +  it('should render correctly when it has an success feedback', () => {
should render correctly when it has A success feedback
sem o n :P

2021-05-14 19:52 UTC, lauralucca approved these changes
LGTM

2021-05-14 20:45 UTC, merged