refactor(natds-react): remove Icon dependency on IconButton and TextField
natura-cosmeticos/natds-js pull request #1665
Opened 2022-02-25 20:06 UTC by mattosdavi

# Description

[[Card]](https://natura.atlassian.net/jira/software/c/projects/DSY/boards/1350?modal=detail&selectedIssue=DSY-2647&assignee=60f4c8ff33876e0068b693b2) - Analisando a arquitetura que temos hoje, isso cria uma dependência entre as duas partes que pode inviabilizar algumas atualizações no futuro. A ideia é que os componentes que dependam do Icon possa recebe-lo como uma propriedade.

## Type of change

- [ ] feat: new feature for the user, not a new feature for build script
- [ ] fix: bug fix for the user, not a fix to a build script
- [ ] docs: changes to the documentation
- [ ] style: formatting, missing semi colons, etc; no production code change
- [ ] refactor: refactoring production code, eg. renaming a variable
- [ ] test: adding missing tests, refactoring tests; no production code   change
- [ ] chore: updating grunt tasks etc; no production code change

# Quality Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or errors;
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] My commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) Guidelines;

2022-02-25 20:12 UTC, mattosdavi commented on packages/react/src/components/Input/InputAction/__snapshots__/InputAction.test.tsx.snap
> +  .wrapper-d1-0-2-5 {  }
Observação: Existe um condicional dentro do InputAction, onde existem sub-componentes que são o TextArea, Input e InputAction. Caso o InputAction é escolhido, a div com classe wrapper é renderizada sem necessidade.

2022-03-02 12:32 UTC, yasminnvaz commented on packages/react/src/components/IconButton/IconButton.test.tsx
> +        IconComponent={<Icon size="standard" name="outlined-default-mockup" color="highEmphasis" />}
não entendi porque repetir aqui se já existe no `iconButtonProps`

2022-03-02 12:42 UTC, yasminnvaz commented on packages/react/src/components/Input/InputAction/__snapshots__/InputAction.test.tsx.snap
> +  .wrapper-d1-0-2-5 {  }
bem observado, Davi! Podemos criar uma card pra corrigir esse problema ;)

2022-03-02 12:45 UTC, yasminnvaz requested changes
depois de revisar os comentários, importante executar os testes de regressão visual

2022-03-03 11:49 UTC, mattosdavi commented on packages/react/src/components/IconButton/IconButton.test.tsx
> +        IconComponent={<Icon size="standard" name="outlined-default-mockup" color="mediumEmphasis" />}
Vou colocar a renderização do componente em uma função e repassar as props. Vai ficar mais fácil de entender e ler quais são as props.

2022-03-04 17:36 UTC, yasminnvaz approved these changes

2022-03-04 19:28 UTC, merged